name: CI/CD
on:
  push:
    branches:
      - master
      - ft/*
      - hf/*
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - name: Update robots.txt for Testing Site
      run: |
        rm ./public/robots.txt
        echo "User-agent: *\nDisallow: /" >> ./public/robots.txt
    - name: Deploy Pull Request to Testing Site
      if: github.event_name == 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TESTING_TOKEN }}
        cname: wdtest.devopsdylan.com
        commit_message: ${{ github.event.head_commit.message }}
        external_repository: westerndevs/western-devs-website-testing
        exclude_assets: 'CNAME'
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: westerndevs.com
        commit_message: ${{ github.event.head_commit.message }}
    - name: Notify Slack
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      
